### ISSUE TITLE
Namespace 'powerbi' has no exported member 'VisualEnumerationInstanceKinds'.ts(2694)

### ISSUE THREAD

**Issue by krngd2** [microsoft/powerbi-visuals-api#24]
I am trying to implement conditional formatting but there is no exported member in 'powerbi-visuals-api'

version
"powerbi-visuals-api": "~2.6.1",
"powerbi-visuals-utils-dataviewutils": "2.2.1"

**Comment by jennyfel** [comment]
Please notice that conditional formatting is supported starting API 3.5.

**Comment by krngd2** [comment]
Hello @jennyfel, 
Thank you for the info. I updated the api to latest version and as soon as I start the dev server, its jumping back to v2.6, 
![image](https://user-images.githubusercontent.com/10483437/120962224-efeb9d00-c77c-11eb-9d8e-31f6fa7f306f.png)
How to fix this ?

**Comment by jennyfel** [comment]
@Nikita Grachev (Akvelon ***@***.***> to assist

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by uve** [comment]
please change the API version on pbiviz.json file

**Comment by krngd2** [comment]
Hello @uve ,
I have manually set the version, deleted node_modules folder and `npm i` . Still right after starting the dev server its jumps back to old version.

**Comment by uve** [comment]
please share the link to your repository, we'll take a look.

**Comment by krngd2** [comment]
Ah sorry @uve, I was changing version in package.json, Now I have changed it in pbiviz.json file and its now upgraded. Thanks
