### ISSUE TITLE
Feat: multiline text

### ISSUE THREAD

**Issue by luizzappa** [microsoft/powerbi-visuals-api#87]
Currently, it is only possible to add text properties to a single line, however, it is a bad experience for the user, especially if needs to break lines.

The property below generates the following field:

```javascript
// capabilities.json
    "objects": {
      "myProp": {
        "properties": {
          "myProp": {
            "type": { "text": true }
          }
        }
      },
```
![image](https://github.com/microsoft/powerbi-visuals-api/assets/65685842/51ee3cff-b229-4d1b-aaa1-916928e518d4)

It would be cool to be able to use a multiline text like the alt text present in the visuals:

![image](https://github.com/microsoft/powerbi-visuals-api/assets/65685842/17341aca-e1a2-4a01-b0c4-aac45a625d05)

**Comment by JOSBALIN** [comment]
Hello,

I believe this is already supported by the formatting setting TextArea. This class extends the TextInput setting and delivers the layout you show in your second image.

The following is the type declaration

`export declare class TextInput extends SimpleSlice<string> {
    placeholder: string;
    type?: visuals.FormattingComponent;
    constructor(object: TextInput);
    getFormattingComponent?(objectName: string): visuals.TextInput;
}
export declare class TextArea extends TextInput {
    type?: visuals.FormattingComponent;
}`


The following is an implementation example:

`    public myText: formattingSettings.TextArea = new formattingSettings.TextArea({
        name: 'myText',
        displayName: 'TextArea',
        value: '',
        placeholder: null
    });`


This is what it looks like:

![image](https://github.com/microsoft/powerbi-visuals-api/assets/71382758/5a837da8-903d-43e7-88e2-f25c43538f5b)



The type in the capabilities should be text, as you correctly defined.

**Comment by luizzappa** [comment]
Works like a charm!
